CREATE TABLE Client (
    clientId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    city VARCHAR(255)
);

INSERT INTO Client (clientId, firstName, lastName, city)
VALUES
    (0, 'John', 'Doe', 'New York'),
    (0, 'Jane', 'Smith', NULL),
    (0, 'Bob', 'Johnson', 'Los Angeles'),
    (0, 'Alice', 'Williams', NULL),
    (0, 'Charlie', 'Brown', 'Chicago'),
    (0, 'David', 'Jones', 'Seattle'),
    (0, 'Emma', 'Taylor', NULL),
    (0, 'Frank', 'Miller', 'San Francisco'),
    (0, 'Grace', 'Davis', 'Miami'),
    (0, 'Henry', 'Moore', NULL),
    (0, 'Isabel', 'Clark', 'Boston'),
    (0, 'Jack', 'White', 'Denver'),
    (0, 'Kelly', 'Lee', NULL),
    (0, 'Leo', 'Allen', 'Dallas'),
    (0, 'Megan', 'Hill', 'Phoenix'),
    (0, 'Nathan', 'Martin', 'Seattle'),
    (0, 'Olivia', 'Young', 'Atlanta'),
    (0, 'Paul', 'Scott', 'Houston'),
    (0, 'Quinn', 'Turner', 'Boston'),
    (0, 'Ryan', 'Ward', 'Portland'),
    (0, 'Sara', 'Garcia', 'Austin'),
    (0, 'Tom', 'Evans', NULL),
    (0, 'Uma', 'Cooper', 'Philadelphia'),
    (0, 'Victor', 'Lopez', 'Las Vegas'),
    (0, 'Wendy', 'Reed', 'Los Angeles'),
    (0, 'Xavier', 'Cruz', 'Detroit'),
    (0, 'Yasmine', 'Chen', 'Minneapolis'),
    (0, 'Zack', 'Nguyen', 'Atlanta'),
    (0, 'Amy', 'Rogers', 'Raleigh'),
    (0, 'Ben', 'Smith', 'Tampa'),
    (0, 'Cathy', 'Anderson', NULL),
    (0, 'Daniel', 'Price', 'Salt Lake City'),
    (0, 'Eva', 'Turner', 'Orlando'),
    (0, 'Felix', 'Morris', 'San Francisco'),
    (0, 'Gina', 'Hughes', 'Charlotte'),
    (0, 'Harry', 'Cooper', 'San Diego'),
    (0, 'Ivy', 'Baker', 'Dallas'),
    (0, 'Jake', 'Fisher', 'Nashville'),
    (0, 'Karen', 'Gomez', 'St. Louis'),
    (0, 'Liam', 'Ross', NULL),
    (0, 'Mia', 'Perez', 'Columbus'),
    (0, 'John', 'Smith', 'Atlanta'),
    (0, 'Alice', 'Ward', 'Houston'),
    (0, 'Emma', 'Hill', 'San Francisco'),
    (0, 'Grace', 'Martin', 'Seattle'),
    (0, 'Isabel', 'Scott', 'Houston'),
    (0, 'Jack', 'Turner', 'Boston'),
    (0, 'Leo', 'Garcia', 'Austin'),
    (0, 'Megan', 'Cooper', 'Philadelphia'),
    (0, 'Olivia', 'Reed', 'Los Angeles'),
    (0, 'Paul', 'Cruz', 'Detroit');