CREATE TABLE Client (
    clientId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    clientName VARCHAR(255) NOT NULL,
    clientLastName VARCHAR(255) NOT NULL
);

INSERT INTO Client (clientId, clientName, clientLastName)
VALUES
    (0, 'John', 'Doe'),
    (0, 'Jane', 'Smith'),
    (0, 'Bob', 'Johnson'),
    (0, 'Alice', 'Williams'),
    (0, 'Charlie', 'Brown'),
    (0, 'David', 'Jones'),
    (0, 'Emma', 'Taylor'),
    (0, 'Frank', 'Miller'),
    (0, 'Grace', 'Davis'),
    (0, 'Henry', 'Moore'),
    (0, 'Isabel', 'Clark'),
    (0, 'Jack', 'White'),
    (0, 'Kelly', 'Lee'),
    (0, 'Leo', 'Allen'),
    (0, 'Megan', 'Hill'),
    (0, 'Nathan', 'Martin'),
    (0, 'Olivia', 'Young'),
    (0, 'Paul', 'Scott'),
    (0, 'Quinn', 'Turner'),
    (0, 'Ryan', 'Ward'),
    (0, 'Sara', 'Garcia'),
    (0, 'Tom', 'Evans'),
    (0, 'Uma', 'Cooper'),
    (0, 'Victor', 'Lopez'),
    (0, 'Wendy', 'Reed'),
    (0, 'Xavier', 'Cruz'),
    (0, 'Yasmine', 'Chen'),
    (0, 'Zack', 'Nguyen'),
    (0, 'Amy', 'Rogers'),
    (0, 'Ben', 'Smith'),
    (0, 'Cathy', 'Anderson'),
    (0, 'Daniel', 'Price'),
    (0, 'Eva', 'Turner'),
    (0, 'Felix', 'Morris'),
    (0, 'Gina', 'Hughes'),
    (0, 'Harry', 'Cooper'),
    (0, 'Ivy', 'Baker'),
    (0, 'Jake', 'Fisher'),
    (0, 'Karen', 'Gomez'),
    (0, 'Liam', 'Ross'),
    (0, 'Mia', 'Perez'),
    (0, 'John', 'Smith'),
    (0, 'Alice', 'Ward'),
    (0, 'Emma', 'Hill'),
    (0, 'Grace', 'Martin'),
    (0, 'Isabel', 'Scott'),
    (0, 'Jack', 'Turner'),
    (0, 'Leo', 'Garcia'),
    (0, 'Megan', 'Cooper'),
    (0, 'Olivia', 'Reed'),
    (0, 'Paul', 'Cruz');